// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsgubhvtiz52k21ylT2Z4Gy-M-RVox7a0',
    appId: '1:631279178693:web:613a15cbf05da5bd3431ac',
    messagingSenderId: '631279178693',
    projectId: 'kinbechfurniture-ed580',
    authDomain: 'kinbechfurniture-ed580.firebaseapp.com',
    storageBucket: 'kinbechfurniture-ed580.appspot.com',
    measurementId: 'G-LKVB6EF0RF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYXnNVb-C2K_XgBMxJCSOS_AGJ8moi5lM',
    appId: '1:631279178693:android:6f8bc7461a7683f23431ac',
    messagingSenderId: '631279178693',
    projectId: 'kinbechfurniture-ed580',
    storageBucket: 'kinbechfurniture-ed580.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvzILpAPY1Lg_IikSyfVfY4GpT9By7e7Q',
    appId: '1:631279178693:ios:b28dbd707898964d3431ac',
    messagingSenderId: '631279178693',
    projectId: 'kinbechfurniture-ed580',
    storageBucket: 'kinbechfurniture-ed580.appspot.com',
    iosBundleId: 'com.kinbech.kinbechFurnitureapp',
  );
}
